### ISSUE TITLE
Syntax error on line 32 of _common-mixins.css?

### ISSUE THREAD

**Issue by LukeNZ** [olivierbossel/gridle#46]
I've just included Gridle 1.3.3 in my project for the first time, and right off the bat, it's not working. Heres the stack trace:

Syntax error: Invalid CSS after "...{$stateName} #{": expected expression (e.g. 1px, bold), was "&}";"
        on line 32 of H:\spacexstatsv4\public\assets\css\gridle\gridle\_common-mixins.scss
        from line 86 of H:\spacexstatsv4\public\assets\css\gridle\gridle\_gridle.scss
        from line 2 of H:\spacexstatsv4\public\assets\css\gridle\_grid-settings.scss
        from line 2 of H:\spacexstatsv4\public\assets\css\gridle\grid.scss
        from line 2 of H:\spacexstatsv4\public\assets\css\styles.scss
  Use --trace for backtrace.

Why is this occurring? 

I'm using Koala 2.0.3 to compile with SASS 3.3.7, for what it's worth...

**Comment by veganista** [comment]
What is the exact version number you are using?

**Comment by juicyfish** [comment]
I'm using sass-3.4.13 and I get the following:

    [18:31:45] Using gulpfile ~/Code/gridle/gulpfile.js
    [18:31:45] Starting 'watch'...
    [18:31:45] Starting 'sass'...
    [18:31:45] Running Sass: resources/assets/sass/grid.scss
    [18:31:45] Finished 'watch' after 410 ms
    [18:31:46] gulp-notify: [Laravel Elixir] Sass Compilation Failed!: error reading values after
    { [Error: error reading values after ]
       message: 'error reading values after ',
       fileName: '/Users/Roger/Code/gridle/resources/assets/sass/gridle/_common-mixins.scss',
       lineNumber: 32,
       showStack: false,
       showProperties: true,
       plugin: 'gulp-sass',
      __safety: { toString: [Function] } }

**Comment by veganista** [comment]
@juicyfish is actually using libsass which currently doesn't have complete feature parity with ruby-sass - #52
